### ISSUE TITLE
Invoice path should be stored relatively to invoices_root_dir

### ISSUE THREAD

**Issue by ambroisemaupate** [BitBagCommerce/SyliusInvoicingPlugin#4]
Once invoice file has been generated, its absolute path is hardcoded in database. This could be a problem if you want to move your Sylius project elsewhere!

Could we just store path relative to `invoices_root_dir` parameter, so that we just store `19be581a08453.pdf` in database. This would much more portable.

**Comment by bitbager** [comment]
Indeed. Could you provide a PR?

**Comment by czende** [comment]
Or even better - render invoice data on the fly with some twig template? That pdf can be stored in var/ directory.

**Comment by ambroisemaupate** [comment]
@czende That’s already working like that. PDF is customizable with Twig template, then you can customize your storage folder. Default to `var/invoices` folder would be better, I agree.

@bitbager I’ll try to find time to create a PR with this issue and a better invoice file naming. Something like `orderId _ orderDate _ randomHash . pdf`
