### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by czende** [BitBagCommerce/SyliusInvoicingPlugin#8]
Hi, when I want to add or edit address in frontstore in my account I'm getting this error:

![screen shot 2018-03-13 at 01 06 14](https://user-images.githubusercontent.com/5628485/37315623-e0c16196-265a-11e8-974e-5f95bd5e9e4a.png)

Moreover I'm still not able to get this plugin works. I've override two twig templates that you are describing in the readme, but still without success. My `bitbag_invoicing_invoice` table is still empty. I'm I missing something? wkhtmltopdf installed, company data filled, billing adress in checkout step filled. Is it supposed to generate invoice after every complete step? I'm on sylius-standard 1.1.1 and invoice-plugin:dev-master. Thx!

**Comment by SteadEXE** [comment]
I am getting the same issue: I have a fresh install and I am getting this exception when I try to add an address to my address book in front store.
